version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/var/log/nginx
    ports:
      - "8080:80"
  
  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme%
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx:/var/log/nginx
    depends_on:
      - elasticsearch
  
  kibana:
    image: kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme%
    ports:
      - "5601:5601"
  
volumes:
  esdata:
